#!/usr/bin/env python3
"""Dump the TWO real state machines straight out of conveyor.py into YAML.

Run this whenever conveyor.py's tables change. It imports the module itself
(never re-types the table), so station.yaml / loop.yaml can't drift from the
implementation the way ten copies of one rule drifted before conveyor.py
existed.

Usage:
    python3 extract_machines.py /path/to/agent-ops-operator
    (writes station.yaml and loop.yaml next to this script)
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import yaml


def load_conveyor(repo_root: Path):
    path = repo_root / ".github" / "scripts" / "conveyor.py"
    spec = importlib.util.spec_from_file_location("conveyor", path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["conveyor"] = mod   # dataclasses needs the module registered before exec
    spec.loader.exec_module(mod)
    return mod


def table_to_transitions(table: dict) -> list[dict]:
    """(state, event) -> next_state  =>  a flat list. `to: null` means SKIP --
    kept, not dropped: conveyor.py's own comment says SKIP is an answer, not
    a gap, and dropping it would misstate which events a state ignores
    versus which are simply undefined (the totality test conveyor.test.py
    runs depends on exactly this distinction)."""
    return [{"from": s, "event": e, "to": nxt} for (s, e), nxt in table.items()]


def build_doc(name: str, subject: str, states: tuple, terminal: list, table: dict) -> dict:
    return {
        "version": 1,
        "generated_from": ".github/scripts/conveyor.py -- do not hand-edit, run extract_machines.py",
        "machine": name,
        "subject": subject,
        "label_family": f"{name}:*",
        "states": list(states),
        "terminal": terminal,
        "transitions": table_to_transitions(table),
    }


class _NoAliasDumper(yaml.SafeDumper):
    """PyYAML aliases repeated strings by default (e.g. every repeated event
    name), which is correct YAML but unreadable for a file meant to be
    diffed and hand-read. Disable it."""
    def ignore_aliases(self, data):
        return True


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 1
    repo_root = Path(sys.argv[1]).resolve()
    out_dir = Path(__file__).resolve().parent
    conveyor = load_conveyor(repo_root)

    station_doc = build_doc("station", "issue", conveyor.STATION_STATES, ["done"], conveyor.STATION_TABLE)
    loop_doc = build_doc("loop", "pull_request", conveyor.LOOP_STATES, [], conveyor.LOOP_TABLE)

    for name, doc in (("station.yaml", station_doc), ("loop.yaml", loop_doc)):
        text = yaml.dump(doc, Dumper=_NoAliasDumper, sort_keys=False, default_flow_style=False)
        (out_dir / name).write_text(
            f"# GENERATED by extract_machines.py from .github/scripts/conveyor.py\n"
            f"# Do not hand-edit -- re-run extract_machines.py after conveyor.py's tables change.\n"
            + text
        )
        print(f"wrote {out_dir / name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
