package chat

import (
	"context"
	"fmt"
	"sort"
	"strconv"
	"sync"
	"sync/atomic"
	"time"

	apimeta "k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"

	agentopsv1alpha1 "github.com/kostiantyn-matsebora/agent-ops-operator/api/v1alpha1"
	"github.com/kostiantyn-matsebora/agent-ops-operator/internal/activity"
)

// OpKind is an outbound channel operation kind.
type OpKind string

const (
	// OpEnsureTopic asks the channel implementation to create a thread for a
	// conversation; completed with the thread id.
	OpEnsureTopic OpKind = "ensure-topic"
	// OpSend asks the channel implementation to post a message.
	OpSend OpKind = "send"
	// OpCloseTopic asks the channel implementation to archive/close a
	// conversation's thread; completed with an empty body.
	//
	// Unlike every other op, the CR it belongs to is on its way out. That is
	// why the deleting Conversation holds a finalizer while this op is
	// outstanding: it keeps "every op is derivable from CR state" true across a
	// manager restart. Failure is TERMINAL — logged, never written as a
	// condition (there is no object left to carry one) and never regenerated
	// after the finalizer's grace expires. An adapter that ignores the kind
	// leaves an open topic behind, which a person can close by hand.
	OpCloseTopic OpKind = "close-topic"
)

// ConditionTopicReady reports the outcome of the latest ensure-topic op.
const ConditionTopicReady = "TopicReady"

// Op is one outbound operation addressed to a channel implementation.
// Delivery is at-least-once; consumers must tolerate duplicates by ID.
type Op struct {
	ID           string  `json:"id"`
	Channel      string  `json:"channel"`
	Conversation string  `json:"conversation,omitempty"`
	Kind         OpKind  `json:"kind"`
	Title        string  `json:"title,omitempty"`    // ensure-topic
	ThreadID     *string `json:"threadId,omitempty"` // send target; nil = general
	Text         string  `json:"text,omitempty"`     // send payload (chat HTML subset)

	channelType string
	enqueuedAt  time.Time
	claimedAt   time.Time // zero = queued
}

// Age reports how long an op has been outstanding since it was enqueued.
func (o *Op) Age() time.Duration { return time.Since(o.enqueuedAt) }

// ClaimedAt is the moment an adapter took the op (zero while still queued).
func (o *Op) ClaimedAt() time.Time { return o.claimedAt }

// ChannelType is the adapter this op is addressed to.
func (o *Op) ChannelType() string { return o.channelType }

// OpResult completes an operation.
type OpResult struct {
	ThreadID string `json:"threadId,omitempty"`
	Error    string `json:"error,omitempty"`
}

// ReclaimAfter returns a claimed-but-never-completed op to the queue (dead
// adapter); ensure-topic ops are additionally regenerated by reconciliation.
const ReclaimAfter = 5 * time.Minute

var sendSeq atomic.Int64

// OpQueue holds pending outbound ops per channel type. In-memory by design:
// every op is derived from CR state (ensure-topic) or is fire-and-forget UX
// (send acks), so queue loss on restart is regenerated or safely dropped.
type OpQueue struct {
	Client    client.Client
	Namespace string
	Registry  *Registry
	// Activity records enqueue and completion hops. Nil is inert.
	Activity *activity.Log

	mu     sync.Mutex
	ops    map[string]*Op      // by id, queued + claimed
	order  map[string][]string // channel type -> queued op ids, FIFO
	recent map[string]bool     // completed ids (dedup window)
	ring   []string            // eviction order for recent
}

func (q *OpQueue) init() {
	if q.ops == nil {
		q.ops = map[string]*Op{}
		q.order = map[string][]string{}
		q.recent = map[string]bool{}
	}
}

// EnqueueEnsureTopic queues topic creation for a conversation on ONE of its
// bound channels. The id is stable per conversation×channel so
// reconcile-driven re-enqueues dedup while one is pending and after
// completion.
func (q *OpQueue) EnqueueEnsureTopic(ctx context.Context, ch *agentopsv1alpha1.Channel, conv *agentopsv1alpha1.Conversation) {
	title := conv.Spec.Title
	if title == "" {
		title = conv.Name
	}
	// ':' keeps the id a single URL path segment for /channel/ops/{id}/done
	q.enqueue(ctx, &Op{
		ID: "topic:" + conv.Name + ":" + ch.Name, Channel: ch.Name, Conversation: conv.Name,
		Kind: OpEnsureTopic, Title: title, channelType: ch.Spec.Adapter,
	})
}

// EnqueueCloseTopic queues archiving of one conversation thread. The id is
// stable per conversation×channel, so the reconciler re-enqueuing it on every
// pass while the finalizer holds dedups instead of piling up.
func (q *OpQueue) EnqueueCloseTopic(ctx context.Context, ch *agentopsv1alpha1.Channel, threadID, conversation string) {
	tid := threadID
	q.enqueue(ctx, &Op{
		ID: CloseTopicOpID(conversation, ch.Name), Channel: ch.Name, Conversation: conversation,
		Kind: OpCloseTopic, ThreadID: &tid, channelType: ch.Spec.Adapter,
	})
}

// CloseTopicOpID is the stable id of a conversation's close-topic op on one
// channel. Exported because the finalizer asks whether it is still outstanding.
func CloseTopicOpID(conversation, channel string) string {
	return "close:" + conversation + ":" + channel
}

// Settled reports whether an op id has already completed within the dedup
// window. Used by the close finalizer to tell "archived" from "never enqueued".
func (q *OpQueue) Settled(id string) bool {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.init()
	return q.recent[id]
}

// EnqueueSend queues a message post (acks, notices). Fire-and-forget.
func (q *OpQueue) EnqueueSend(ctx context.Context, ch *agentopsv1alpha1.Channel, threadID *string, text string) {
	q.enqueue(ctx, &Op{
		ID: "send:" + strconv.FormatInt(sendSeq.Add(1), 36), Channel: ch.Name,
		Kind: OpSend, ThreadID: threadID, Text: text, channelType: ch.Spec.Adapter,
	})
}

func (q *OpQueue) enqueue(ctx context.Context, op *Op) {
	q.mu.Lock()
	q.init()
	// Dedup by id for the derived kinds: already pending, a completed
	// ensure-topic racing its status patch, or a close-topic the finalizer
	// re-derives on every pass until it lets go. Sends carry a fresh id each
	// time and are never suppressed.
	if q.ops[op.ID] != nil || (op.Kind != OpSend && q.recent[op.ID]) {
		q.mu.Unlock()
		return
	}
	op.enqueuedAt = time.Now()
	q.ops[op.ID] = op
	q.order[op.channelType] = append(q.order[op.channelType], op.ID)
	q.mu.Unlock()

	// Enqueued is INTENT, not delivery. The console renders this edge as "sent,
	// unconfirmed" until a channel.op.completed arrives — a dedup that silently
	// suppressed the op emits nothing, so the graph never shows a hop that did
	// not happen.
	q.Activity.Emit(activity.Event{
		Kind:         activity.KindChannelOpEnqueued,
		From:         opOriginNode(op),
		To:           activity.Node(activity.NodeChannel, op.Channel),
		Conversation: op.Conversation, OpID: op.ID, Code: string(op.Kind), Detail: op.Channel,
	})

	// in-process types execute immediately through the same claim/complete
	// path; detached from the caller's (request-scoped) context
	if f := q.registryResolve(op.channelType); f != nil {
		go func() {
			runCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 30*time.Second)
			defer cancel()
			q.runInProcess(runCtx, op.channelType, f)
		}()
	}
}

func (q *OpQueue) registryResolve(channelType string) ProviderFactory {
	if q.Registry == nil {
		return nil
	}
	return q.Registry.Resolve(channelType)
}

func (q *OpQueue) runInProcess(ctx context.Context, channelType string, f ProviderFactory) {
	op := q.Claim(channelType)
	if op == nil {
		return
	}
	res := OpResult{}
	p, err := f(ctx, op.Channel)
	if err == nil {
		switch op.Kind {
		case OpEnsureTopic:
			res.ThreadID, err = p.EnsureTopic(ctx, op.Title)
		case OpSend:
			err = p.Send(ctx, op.ThreadID, op.Text)
		case OpCloseTopic:
			if closer, ok := p.(TopicCloser); ok && op.ThreadID != nil {
				err = closer.CloseTopic(ctx, *op.ThreadID)
			}
		}
	}
	if err != nil {
		res.Error = err.Error()
	}
	q.Complete(ctx, op.ID, res)
}

// Claim pops the oldest queued op for a channel type (nil when empty) and
// marks it claimed; unfinished claims are re-queued after ReclaimAfter.
func (q *OpQueue) Claim(channelType string) *Op {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.init()
	// return timed-out claims to the front of the queue
	for id, op := range q.ops {
		if op.channelType == channelType && !op.claimedAt.IsZero() && time.Since(op.claimedAt) > ReclaimAfter {
			op.claimedAt = time.Time{}
			q.order[channelType] = append([]string{id}, q.order[channelType]...)
		}
	}
	queue := q.order[channelType]
	for len(queue) > 0 {
		id := queue[0]
		queue = queue[1:]
		if op := q.ops[id]; op != nil && op.claimedAt.IsZero() {
			op.claimedAt = time.Now()
			q.order[channelType] = queue
			cp := *op
			return &cp
		}
	}
	q.order[channelType] = queue
	return nil
}

// Complete finishes an op. Unknown or already-completed ids are tolerated
// (at-least-once delivery makes duplicate completions legal).
func (q *OpQueue) Complete(ctx context.Context, id string, res OpResult) {
	q.mu.Lock()
	q.init()
	op := q.ops[id]
	if op == nil {
		q.mu.Unlock()
		return
	}
	delete(q.ops, id)
	q.recent[id] = true
	q.ring = append(q.ring, id)
	if len(q.ring) > 512 {
		delete(q.recent, q.ring[0])
		q.ring = q.ring[1:]
	}
	q.mu.Unlock()

	// The manager's own view of delivery. An adapter that also POSTs /activity
	// reports the latency it measured on the wire; this one is queue-to-ack.
	done := activity.Event{
		Kind: activity.KindChannelOpCompleted,
		From: activity.Node(activity.NodeChannelAdapter, op.channelType),
		// The CHANNEL, not the manager: the adapter delivered to that surface,
		// which is both what happened and something the graph can draw. Naming
		// the manager made this hop unrenderable — the manager is not a wiring
		// node, so the served-by edge every reply travels never lit up.
		To:           activity.Node(activity.NodeChannel, op.Channel),
		Conversation: op.Conversation, OpID: op.ID, Code: string(op.Kind),
		Detail:    op.Channel,
		LatencyMs: time.Since(op.enqueuedAt).Milliseconds(),
	}
	if res.Error != "" {
		done.Status = activity.StatusError
		done.Detail = op.Channel + ": " + res.Error
	}
	q.Activity.Emit(done)

	switch {
	case op.Kind == OpEnsureTopic:
		if err := q.finishEnsureTopic(ctx, op, res); err != nil {
			log.FromContext(ctx).Error(err, "complete ensure-topic", "conversation", op.Conversation)
			// drop the dedup entry so reconciliation can regenerate the op
			q.mu.Lock()
			delete(q.recent, id)
			q.mu.Unlock()
		}
	case op.Kind == OpCloseTopic:
		// Terminal either way: an empty body means archived, an error means the
		// thread stays open. No condition is written — the Conversation is being
		// deleted, so there is no object left to carry one — and the op is NOT
		// regenerated. The finalizer releases regardless.
		if res.Error != "" {
			log.FromContext(ctx).Info("close-topic op failed; leaving the thread open",
				"channel", op.Channel, "conversation", op.Conversation, "error", res.Error)
		}
	case res.Error != "":
		log.FromContext(ctx).Info("send op failed", "channel", op.Channel, "error", res.Error)
	}
}

func (q *OpQueue) finishEnsureTopic(ctx context.Context, op *Op, res OpResult) error {
	var conv agentopsv1alpha1.Conversation
	if err := q.Client.Get(ctx, types.NamespacedName{Namespace: q.Namespace, Name: op.Conversation}, &conv); err != nil {
		return client.IgnoreNotFound(err)
	}
	patch := client.MergeFrom(conv.DeepCopy())
	cond := metav1.Condition{Type: ConditionTopicReady, Status: metav1.ConditionTrue, Reason: "TopicCreated",
		Message: "channel " + op.Channel}
	if res.Error != "" {
		cond.Status = metav1.ConditionFalse
		cond.Reason = "AdapterError"
		cond.Message = "channel " + op.Channel + ": " + res.Error
	} else if res.ThreadID == "" {
		cond.Status = metav1.ConditionFalse
		cond.Reason = "AdapterError"
		cond.Message = "channel " + op.Channel + ": adapter completed ensure-topic without a thread id"
	} else if conv.ThreadFor(op.Channel) == nil {
		conv.Status.Threads = append(conv.Status.Threads, agentopsv1alpha1.ThreadBinding{
			Channel: op.Channel, ThreadID: res.ThreadID,
		})
	}
	apimeta.SetStatusCondition(&conv.Status.Conditions, cond)
	if err := q.Client.Status().Patch(ctx, &conv, patch); err != nil {
		return err
	}
	if cond.Status == metav1.ConditionFalse {
		return fmt.Errorf("ensure-topic for %s: %s", op.Conversation, cond.Message)
	}
	return nil
}

// Pending reports whether an op is queued or claimed (used by tests).
func (q *OpQueue) Pending(id string) bool {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.init()
	return q.ops[id] != nil
}

// opOriginNode names where an op came from. A conversation-bound op flows from
// its conversation; a bare notice (an unwired-source warning on a general
// surface) flows from the manager.
func opOriginNode(op *Op) *activity.NodeRef {
	if op.Conversation != "" {
		return activity.Node(activity.NodeConversation, op.Conversation)
	}
	return activity.Node(activity.NodeManager, activity.NodeManager)
}

// QueueStat is one adapter's outstanding-op picture: how deep, how old, and
// WHICH op is the oldest of each kind. The identities live here rather than in
// a metric label, because a conversation or op id as a label grows series
// without bound — metrics answer "how deep, how old", this answers "which one".
type QueueStat struct {
	Adapter string `json:"adapter"`
	// Queued ops wait for an adapter to claim them: deep-and-old means nothing
	// is polling.
	Queued int `json:"queued"`
	// Claimed ops were taken and never completed: deep-and-old means an adapter
	// is wedged mid-delivery. The two failure modes look identical from outside,
	// which is exactly why they are counted apart.
	Claimed             int     `json:"claimed"`
	OldestQueuedOpID    string  `json:"oldestQueuedOpId,omitempty"`
	OldestQueuedAgeSecs float64 `json:"oldestQueuedAgeSeconds,omitempty"`
	OldestQueuedConv    string  `json:"oldestQueuedConversation,omitempty"`

	OldestClaimedOpID    string  `json:"oldestClaimedOpId,omitempty"`
	OldestClaimedAgeSecs float64 `json:"oldestClaimedAgeSeconds,omitempty"`
	OldestClaimedConv    string  `json:"oldestClaimedConversation,omitempty"`
}

// Stats snapshots the queue per adapter. The OpQueue is in-memory by design, so
// this is the ONLY place these facts exist — no Kubernetes object carries them.
func (q *OpQueue) Stats() []QueueStat {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.init()
	byAdapter := map[string]*QueueStat{}
	oldestQueued := map[string]time.Time{}
	oldestClaimed := map[string]time.Time{}
	for _, op := range q.ops {
		st := byAdapter[op.channelType]
		if st == nil {
			st = &QueueStat{Adapter: op.channelType}
			byAdapter[op.channelType] = st
		}
		if op.claimedAt.IsZero() {
			st.Queued++
			if t, ok := oldestQueued[op.channelType]; !ok || op.enqueuedAt.Before(t) {
				oldestQueued[op.channelType] = op.enqueuedAt
				st.OldestQueuedOpID, st.OldestQueuedConv = op.ID, op.Conversation
				st.OldestQueuedAgeSecs = time.Since(op.enqueuedAt).Seconds()
			}
			continue
		}
		st.Claimed++
		if t, ok := oldestClaimed[op.channelType]; !ok || op.claimedAt.Before(t) {
			oldestClaimed[op.channelType] = op.claimedAt
			st.OldestClaimedOpID, st.OldestClaimedConv = op.ID, op.Conversation
			st.OldestClaimedAgeSecs = time.Since(op.claimedAt).Seconds()
		}
	}
	out := make([]QueueStat, 0, len(byAdapter))
	for _, st := range byAdapter {
		out = append(out, *st)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Adapter < out[j].Adapter })
	return out
}
