package chat

import (
	"context"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	apierrors "k8s.io/apimachinery/pkg/api/errors"
	apimeta "k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"

	agentopsv1alpha1 "github.com/kostiantyn-matsebora/agent-ops-operator/api/v1alpha1"
	"github.com/kostiantyn-matsebora/agent-ops-operator/internal/activity"
)

// OpKind is an outbound channel operation kind.
type OpKind string

const (
	// OpEnsureTopic asks the channel implementation to create a thread for a
	// conversation; completed with the thread id.
	OpEnsureTopic OpKind = "ensure-topic"
	// OpSend asks the channel implementation to post a message.
	OpSend OpKind = "send"
	// OpCloseTopic asks the channel implementation to archive/close a
	// conversation's thread; completed with an empty body.
	//
	// Enqueued when a conversation reaches phase Closed, and recorded in
	// status.threadsArchived[] — which is what makes it re-derivable, since the
	// object survives its close. An adapter that ignores the kind leaves an
	// open topic behind, which a person can close by hand.
	OpCloseTopic OpKind = "close-topic"
	// OpDeleteConversation reports that a Conversation is gone for good;
	// completed with an empty body. Carries the thread id and a notice.
	//
	// It REPORTS A FACT rather than instructing an adapter about a thread,
	// which is why it is named for the conversation: what ending means for a
	// thread is the adapter's decision — post a tombstone, archive, rename,
	// delete. Telegram cannot even post into an archived topic without
	// un-archiving first, and that is precisely the knowledge the manager does
	// not have.
	//
	// It REPLACES close-topic on the deletion path. A conversation being
	// deleted gets one or the other, never both, so no adapter has to work out
	// whether a pair means one ending or two.
	//
	// Unlike close-topic this is NOT derivable: the CR it belongs to is
	// disappearing, so there is nowhere to record what is owed. The deleting
	// Conversation holds a finalizer while it is outstanding, and failure is
	// TERMINAL — logged, never a condition, never regenerated once the grace
	// expires. A deletion must never wedge on a down adapter.
	OpDeleteConversation OpKind = "delete-conversation"
)

// ConditionTopicReady reports the outcome of the latest ensure-topic op.
const ConditionTopicReady = "TopicReady"

// Op is one outbound operation addressed to a channel implementation.
// Delivery is at-least-once; consumers must tolerate duplicates by ID.
//
// The payload is STRUCTURED, never rendered: `Message` says what is being
// communicated and `Topic` describes the thread to create. The adapter turns
// either into whatever its surface speaks. See message.go for why.
type Op struct {
	ID           string  `json:"id"`
	Channel      string  `json:"channel"`
	Conversation string  `json:"conversation,omitempty"`
	Kind         OpKind  `json:"kind"`
	ThreadID     *string `json:"threadId,omitempty"` // send target; nil = general

	// Topic describes the thread to create (ensure-topic only).
	Topic *TopicDescriptor `json:"topic,omitempty"`
	// Message is the semantic message to post (send only).
	Message *Message `json:"message,omitempty"`

	channelType string
	enqueuedAt  time.Time
	claimedAt   time.Time // zero = queued
	// stable marks an op whose id is DERIVED from CR state, so reconciliation
	// re-enqueues it on every pass and it must dedup against the completed
	// window as well as the pending map. Ephemeral sends (acks, notices) carry a
	// fresh id each time and are never suppressed — saying the same thing twice
	// is correct when a user asked twice.
	stable bool
}

// Age reports how long an op has been outstanding since it was enqueued.
func (o *Op) Age() time.Duration { return time.Since(o.enqueuedAt) }

// ClaimedAt is the moment an adapter took the op (zero while still queued).
func (o *Op) ClaimedAt() time.Time { return o.claimedAt }

// ChannelType is the adapter this op is addressed to.
func (o *Op) ChannelType() string { return o.channelType }

// OpResult completes an operation.
type OpResult struct {
	ThreadID string `json:"threadId,omitempty"`
	Error    string `json:"error,omitempty"`
}

// ReclaimAfter returns a claimed-but-never-completed op to the queue (dead
// adapter); ensure-topic ops are additionally regenerated by reconciliation.
const ReclaimAfter = 5 * time.Minute

var sendSeq atomic.Int64

// OpQueue holds pending outbound ops per channel type. In-memory by design and
// NEVER the record of what is owed: every op is either DERIVED from CR state —
// ensure-topic from a missing thread binding, an input card from an unposted
// input, a run reply from a run without a delivery marker — or is
// fire-and-forget UX (acks, notices) whose loss costs nothing. Queue loss on
// restart is therefore regenerated or safely dropped.
//
// `close-topic` is the one exception, and it is exceptional because the object
// that would carry the obligation is being deleted. See OpCloseTopic.
type OpQueue struct {
	Client    client.Client
	Namespace string
	Registry  *Registry
	// Activity records enqueue and completion hops. Nil is inert.
	Activity *activity.Log

	mu     sync.Mutex
	ops    map[string]*Op      // by id, queued + claimed
	order  map[string][]string // channel type -> queued op ids, FIFO
	recent map[string]bool     // completed ids (dedup window)
	ring   []string            // eviction order for recent
}

func (q *OpQueue) init() {
	if q.ops == nil {
		q.ops = map[string]*Op{}
		q.order = map[string][]string{}
		q.recent = map[string]bool{}
	}
}

// EnqueueEnsureTopic queues topic creation for a conversation on ONE of its
// bound channels. The id is stable per conversation×channel so
// reconcile-driven re-enqueues dedup while one is pending and after
// completion.
// The descriptor carries the same facts as the first card in the thread, so an
// adapter can choose not to repeat itself — the alert name in the topic, the
// labels in the card — and can enforce its own naming limits (Telegram forum
// topics cap at 128 characters) instead of receiving a title already cut to a
// length the manager guessed at.
func (q *OpQueue) EnqueueEnsureTopic(ctx context.Context, ch *agentopsv1alpha1.Channel, conv *agentopsv1alpha1.Conversation, topic TopicDescriptor) {
	topic.Conversation = conv.Name
	if topic.Title == "" {
		topic.Title = conv.Spec.Title
	}
	if topic.Title == "" {
		topic.Title = conv.Name
	}
	// ':' keeps the id a single URL path segment for /channel/ops/{id}/done.
	// The reopen counter keeps the id STABLE (so reconciliation re-derives it)
	// while making each reopen's request distinct — without it a reopen's
	// ensure-topic dedups against the original topic creation and never reaches
	// the adapter.
	id := "topic:" + conv.Name + ":" + ch.Name
	if conv.Status.Reopens > 0 {
		id += ":r" + strconv.Itoa(int(conv.Status.Reopens))
	}
	q.enqueue(ctx, &Op{
		ID: id, Channel: ch.Name, Conversation: conv.Name,
		Kind: OpEnsureTopic, Topic: &topic, channelType: ch.Spec.Adapter, stable: true,
	})
}

// EnqueueCloseTopic queues archiving of one conversation thread. The id is
// stable per conversation×channel, so the reconciler re-enqueuing it on every
// pass while the finalizer holds dedups instead of piling up.
func (q *OpQueue) EnqueueCloseTopic(ctx context.Context, ch *agentopsv1alpha1.Channel, threadID, conversation string) {
	tid := threadID
	q.enqueue(ctx, &Op{
		ID: CloseTopicOpID(conversation, ch.Name), Channel: ch.Name, Conversation: conversation,
		Kind: OpCloseTopic, ThreadID: &tid, channelType: ch.Spec.Adapter, stable: true,
	})
}

// CloseTopicOpID is the stable id of a conversation's close-topic op on one
// channel. Exported because the finalizer asks whether it is still outstanding.
func CloseTopicOpID(conversation, channel string) string {
	return "close:" + conversation + ":" + channel
}

// EnqueueDeleteConversation tells one bound thread that its conversation is
// gone for good.
//
// The MESSAGE is composed here and rendered by the adapter, like every other
// message: the manager states what happened, and escaping, splitting and
// placement belong to whoever knows the transport. An adapter is free to ignore
// the text and express the ending structurally instead.
func (q *OpQueue) EnqueueDeleteConversation(ctx context.Context, ch *agentopsv1alpha1.Channel, threadID, conversation string) {
	tid := threadID
	msg := Notice("🗑 This conversation has been deleted, along with everything it recorded. " +
		"The thread stays here to read. A new message starts a NEW conversation — it will not continue this one.")
	q.enqueue(ctx, &Op{
		ID: DeleteConversationOpID(conversation, ch.Name), Channel: ch.Name, Conversation: conversation,
		Kind: OpDeleteConversation, ThreadID: &tid, Message: &msg,
		channelType: ch.Spec.Adapter, stable: true,
	})
}

// DeleteConversationOpID is the stable id of a conversation's
// delete-conversation op on one channel. The finalizer asks whether it is still
// outstanding.
func DeleteConversationOpID(conversation, channel string) string {
	return "gone:" + conversation + ":" + channel
}

// ParseCloseTopicOpID splits a close-topic op id back into its parts. Channel
// names cannot contain ":" (they are Kubernetes object names), so the split is
// unambiguous.
func ParseCloseTopicOpID(id string) (conversation, channel string, ok bool) {
	parts := strings.Split(id, ":")
	if len(parts) != 3 || parts[0] != "close" {
		return "", "", false
	}
	return parts[1], parts[2], true
}

// Settled reports whether an op id has already completed within the dedup
// window. Used by the close finalizer to tell "archived" from "never enqueued".
func (q *OpQueue) Settled(id string) bool {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.init()
	return q.recent[id]
}

// EnqueueMessage queues one semantic message. Fire-and-forget: the id is fresh
// each time, so sends are never suppressed by dedup.
//
// Callers pass a Message built by one of the kind constructors in message.go
// (Notice, Warn, AnswerMessage, RelayMessage, SignalMessage) — there is no
// string-valued form on purpose, because that is what let transport markup back
// into the manager.
func (q *OpQueue) EnqueueMessage(ctx context.Context, ch *agentopsv1alpha1.Channel, threadID *string, msg Message) {
	q.enqueueMessage(ctx, "send:"+strconv.FormatInt(sendSeq.Add(1), 36), ch, "", threadID, msg, false)
}

// EnqueueFarewell posts a conversation's closing notice with a STABLE id, so a
// close that is attempted more than once says goodbye exactly once.
//
// This is not hypothetical tidiness. The farewell is posted before the status
// write — deliberately, because a conversation whose thread simply stops is
// indistinguishable from a fault, so a lost farewell is worse than a repeated
// one — and a close whose status write FAILS is retried. A live smoke against a
// cluster whose CRD did not yet allow phase `Closed` put four farewells in one
// thread over seven hours of retries. An ephemeral id makes every retry a new
// message; a stable one makes them the same message.
//
// Keyed on the reopen count as well, for the same reason ensure-topic is: a
// conversation closed, reopened and closed again is owed a SECOND farewell, and
// a genuinely stable id would suppress it.
func (q *OpQueue) EnqueueFarewell(ctx context.Context, ch *agentopsv1alpha1.Channel,
	conv *agentopsv1alpha1.Conversation, threadID *string, msg Message) {
	id := fmt.Sprintf("farewell:%s:%s:%d", conv.Name, ch.Name, conv.Status.Reopens)
	q.enqueueMessage(ctx, id, ch, conv.Name, threadID, msg, true)
}

// EnqueueReopenNotice announces that a conversation is live again, on every
// bound thread.
//
// The MANAGER says this, not each adapter. A closing thread already gets a
// farewell from here, and a reopen is the same kind of fact — so synthesizing
// it adapter-side would put it on whichever surface happened to implement it
// and leave the others with a thread that silently starts working again. It is
// also the rule: the manager composes meaning, adapters compose presentation.
//
// Stable per reopen, so reconciliation may re-derive it on every pass and it
// still lands once — and a SECOND reopen gets its own.
func (q *OpQueue) EnqueueReopenNotice(ctx context.Context, ch *agentopsv1alpha1.Channel,
	conv *agentopsv1alpha1.Conversation, threadID *string, msg Message) {
	id := fmt.Sprintf("reopened:%s:%s:%d", conv.Name, ch.Name, conv.Status.Reopens)
	q.enqueueMessage(ctx, id, ch, conv.Name, threadID, msg, true)
}

// EnqueueInputCard queues the card for one input on one channel. Unlike an
// ordinary send its id is STABLE per conversation×input×channel, so the
// reconciler re-deriving it on every pass dedups against both the pending map
// and the recent window — exactly as ensure-topic already does. Without that, a
// conversation would repost its alert on every reconcile.
func (q *OpQueue) EnqueueInputCard(ctx context.Context, ch *agentopsv1alpha1.Channel,
	conversation, inputID string, threadID *string, msg Message) {

	q.enqueueMessage(ctx, InputCardOpID(conversation, inputID, ch.Name), ch, conversation, threadID, msg, true)
}

// InputCardOpID is the stable id of one input's card on one channel.
func InputCardOpID(conversation, inputID, channel string) string {
	return "input:" + conversation + ":" + inputID + ":" + channel
}

// EnqueueRunReply queues one run's answer on one channel. Its id is STABLE per
// conversation×channel×run, which is what makes the reply derivable: `/work/done`
// enqueues it on the fast path and reconciliation re-enqueues it for any bound
// thread still lacking a delivery marker, and the two dedup against each other
// through the pending map and the completed window.
//
// Ack and notice sends stay on the counter-based id: saying the same thing twice
// is correct when a user asked twice, and neither derives from CR state.
func (q *OpQueue) EnqueueRunReply(ctx context.Context, ch *agentopsv1alpha1.Channel,
	conversation, runID string, threadID *string, msg Message) {

	q.enqueueMessage(ctx, RunReplyOpID(conversation, ch.Name, runID), ch, conversation, threadID, msg, true)
}

// RunReplyOpID is the stable id of one run's reply on one channel. Exported
// because completion has to map the op back to the run it delivers.
func RunReplyOpID(conversation, channel, runID string) string {
	return "send:" + conversation + ":" + channel + ":" + runID
}

// ParseRunReplyOpID splits a reply op id back into its parts, reporting false
// for any other id. Completion uses it to mark the run/channel pair delivered
// without the op having to carry redundant fields.
func ParseRunReplyOpID(id string) (conversation, channel, runID string, ok bool) {
	parts := strings.Split(id, ":")
	// Conversation and channel are Kubernetes object names, so they cannot
	// contain ':'; a run id could in principle, so the REMAINDER is the run.
	if len(parts) < 4 || parts[0] != "send" {
		return "", "", "", false
	}
	return parts[1], parts[2], strings.Join(parts[3:], ":"), true
}

func (q *OpQueue) enqueueMessage(ctx context.Context, id string, ch *agentopsv1alpha1.Channel,
	conversation string, threadID *string, msg Message, stable bool) {

	q.enqueue(ctx, &Op{
		ID: id, Channel: ch.Name, Conversation: conversation,
		Kind: OpSend, ThreadID: threadID, Message: &msg, channelType: ch.Spec.Adapter, stable: stable,
	})
}

func (q *OpQueue) enqueue(ctx context.Context, op *Op) {
	q.mu.Lock()
	q.init()
	// Dedup by id for the DERIVED ops: already pending, a completed
	// ensure-topic racing its status patch, a close-topic the finalizer
	// re-derives until it lets go, or an input card the reconciler re-derives on
	// every pass. Ephemeral sends carry a fresh id each time and are never
	// suppressed. Keying this on `stable` rather than on Kind is what lets an
	// input card be a send AND survive re-enqueue without duplicating.
	if q.ops[op.ID] != nil || (op.stable && q.recent[op.ID]) {
		q.mu.Unlock()
		return
	}
	op.enqueuedAt = time.Now()
	q.ops[op.ID] = op
	q.order[op.channelType] = append(q.order[op.channelType], op.ID)
	q.mu.Unlock()

	// Enqueued is INTENT, not delivery. The console renders this edge as "sent,
	// unconfirmed" until a channel.op.completed arrives — a dedup that silently
	// suppressed the op emits nothing, so the graph never shows a hop that did
	// not happen.
	q.Activity.Emit(activity.Event{
		Kind:         activity.KindChannelOpEnqueued,
		From:         opOriginNode(op),
		To:           activity.Node(activity.NodeChannel, op.Channel),
		Conversation: op.Conversation, OpID: op.ID, Code: string(op.Kind), Detail: op.Channel,
	})

	// in-process types execute immediately through the same claim/complete
	// path; detached from the caller's (request-scoped) context
	if f := q.registryResolve(op.channelType); f != nil {
		go func() {
			runCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 30*time.Second)
			defer cancel()
			q.runInProcess(runCtx, op.channelType, f)
		}()
	}
}

func (q *OpQueue) registryResolve(channelType string) ProviderFactory {
	if q.Registry == nil {
		return nil
	}
	return q.Registry.Resolve(channelType)
}

func (q *OpQueue) runInProcess(ctx context.Context, channelType string, f ProviderFactory) {
	op := q.Claim(channelType)
	if op == nil {
		return
	}
	res := OpResult{}
	p, err := f(ctx, op.Channel)
	if err == nil {
		switch op.Kind {
		case OpEnsureTopic:
			if op.Topic != nil {
				res.ThreadID, err = p.EnsureTopic(ctx, *op.Topic)
			}
		case OpSend:
			if op.Message != nil {
				err = p.Send(ctx, op.ThreadID, *op.Message)
			}
		case OpCloseTopic:
			if closer, ok := p.(TopicCloser); ok && op.ThreadID != nil {
				err = closer.CloseTopic(ctx, *op.ThreadID)
			}
		}
	}
	if err != nil {
		res.Error = err.Error()
	}
	q.Complete(ctx, op.ID, res)
}

// Claim pops the oldest queued op for a channel type (nil when empty) and
// marks it claimed; unfinished claims are re-queued after ReclaimAfter.
func (q *OpQueue) Claim(channelType string) *Op {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.init()
	// return timed-out claims to the front of the queue
	for id, op := range q.ops {
		if op.channelType == channelType && !op.claimedAt.IsZero() && time.Since(op.claimedAt) > ReclaimAfter {
			op.claimedAt = time.Time{}
			q.order[channelType] = append([]string{id}, q.order[channelType]...)
		}
	}
	queue := q.order[channelType]
	for len(queue) > 0 {
		id := queue[0]
		queue = queue[1:]
		if op := q.ops[id]; op != nil && op.claimedAt.IsZero() {
			op.claimedAt = time.Now()
			q.order[channelType] = queue
			cp := *op
			return &cp
		}
	}
	q.order[channelType] = queue
	return nil
}

// Complete finishes an op. Unknown or already-completed ids are tolerated
// (at-least-once delivery makes duplicate completions legal).
func (q *OpQueue) Complete(ctx context.Context, id string, res OpResult) {
	q.mu.Lock()
	q.init()
	op := q.ops[id]
	if op == nil {
		q.mu.Unlock()
		return
	}
	delete(q.ops, id)
	q.recent[id] = true
	q.ring = append(q.ring, id)
	if len(q.ring) > 512 {
		delete(q.recent, q.ring[0])
		q.ring = q.ring[1:]
	}
	q.mu.Unlock()

	// The manager's own view of delivery. An adapter that also POSTs /activity
	// reports the latency it measured on the wire; this one is queue-to-ack.
	done := activity.Event{
		Kind: activity.KindChannelOpCompleted,
		From: activity.Node(activity.NodeChannelAdapter, op.channelType),
		// The CHANNEL, not the manager: the adapter delivered to that surface,
		// which is both what happened and something the graph can draw. Naming
		// the manager made this hop unrenderable — the manager is not a wiring
		// node, so the served-by edge every reply travels never lit up.
		To:           activity.Node(activity.NodeChannel, op.Channel),
		Conversation: op.Conversation, OpID: op.ID, Code: string(op.Kind),
		Detail:    op.Channel,
		LatencyMs: time.Since(op.enqueuedAt).Milliseconds(),
	}
	if res.Error != "" {
		done.Status = activity.StatusError
		done.Detail = op.Channel + ": " + res.Error
	}
	q.Activity.Emit(done)

	switch {
	case op.Kind == OpEnsureTopic:
		if err := q.finishEnsureTopic(ctx, op, res); err != nil {
			log.FromContext(ctx).Error(err, "complete ensure-topic", "conversation", op.Conversation)
			// drop the dedup entry so reconciliation can regenerate the op
			q.mu.Lock()
			delete(q.recent, id)
			q.mu.Unlock()
		}
	case op.Kind == OpSend && res.Error == "" && isRunReply(op.ID):
		// Delivery becomes a FACT on the conversation. Marking on completion
		// rather than on enqueue is what makes the two paths safe: an op lost
		// before completion is re-derived by reconciliation, and one completed
		// before a restart is not.
		if err := q.markDelivered(ctx, op); err != nil {
			log.FromContext(ctx).Error(err, "mark run reply delivered", "conversation", op.Conversation, "op", op.ID)
			// Unmark the dedup entry: an undelivered marker with a suppressed op
			// would leave the answer owed and unenqueueable.
			q.mu.Lock()
			delete(q.recent, id)
			q.mu.Unlock()
		}
	case op.Kind == OpDeleteConversation:
		// Terminal either way, and never regenerated: the Conversation is on
		// its way out, so there is no object left to carry a condition and
		// nothing to re-derive from. The finalizer's grace releases regardless.
		if res.Error != "" {
			log.FromContext(ctx).Info("delete-conversation op failed; the thread was not told",
				"channel", op.Channel, "conversation", op.Conversation, "error", res.Error)
		}
	case op.Kind == OpCloseTopic:
		// Archiving became a FACT on the conversation when closing stopped
		// deleting. The object survives the close, so there is something to
		// record against — which is what retires close-topic's old status as
		// the one op not derivable from CR state.
		if res.Error == "" {
			if err := q.markThreadArchived(ctx, op); err != nil {
				log.FromContext(ctx).Error(err, "mark thread archived",
					"conversation", op.Conversation, "op", op.ID)
				q.mu.Lock()
				delete(q.recent, id)
				q.mu.Unlock()
			}
			break
		}
		// Failed: release the dedup entry so reconciliation re-derives it. A
		// conversation being DELETED has no marker to gain and no object left
		// to re-derive from — the finalizer's grace covers that path and
		// releases regardless, so this costs it nothing.
		log.FromContext(ctx).Info("close-topic op failed; leaving the thread open",
			"channel", op.Channel, "conversation", op.Conversation, "error", res.Error)
		q.mu.Lock()
		delete(q.recent, id)
		q.mu.Unlock()
	case res.Error != "":
		log.FromContext(ctx).Info("send op failed", "channel", op.Channel, "error", res.Error)
	}
}

// isRunReply reports whether an op id is a stable run-reply id.
func isRunReply(id string) bool {
	_, _, _, ok := ParseRunReplyOpID(id)
	return ok
}

// markThreadArchived records that one bound thread has been archived, so
// reconciliation stops re-deriving its close-topic op. Mirrors markDelivered,
// including the conflict retry: a close races the next status write.
//
// A conversation on its way out is tolerated as NotFound — the finalizer path
// has no object to mark and does not need one.
func (q *OpQueue) markThreadArchived(ctx context.Context, op *Op) error {
	_, channel, ok := ParseCloseTopicOpID(op.ID)
	if !ok || q.Client == nil {
		return nil
	}
	for attempt := 0; attempt < 5; attempt++ {
		var conv agentopsv1alpha1.Conversation
		if err := q.Client.Get(ctx, types.NamespacedName{Namespace: q.Namespace, Name: op.Conversation}, &conv); err != nil {
			return client.IgnoreNotFound(err)
		}
		if conv.Status.ThreadArchived(channel) {
			return nil
		}
		patch := client.MergeFrom(conv.DeepCopy())
		conv.Status.ThreadsArchived = append(conv.Status.ThreadsArchived, channel)
		err := q.Client.Status().Patch(ctx, &conv, patch)
		if err == nil {
			return nil
		}
		if !apierrors.IsConflict(err) {
			return client.IgnoreNotFound(err)
		}
	}
	return nil
}

// markDelivered records that a run's reply reached one channel's thread, so
// reconciliation stops re-deriving it. Retried on conflict: the reply and the
// next run's status write compete for the same subresource.
func (q *OpQueue) markDelivered(ctx context.Context, op *Op) error {
	_, channel, runID, ok := ParseRunReplyOpID(op.ID)
	if !ok {
		return nil
	}
	for attempt := 0; attempt < 5; attempt++ {
		var conv agentopsv1alpha1.Conversation
		if err := q.Client.Get(ctx, types.NamespacedName{Namespace: q.Namespace, Name: op.Conversation}, &conv); err != nil {
			return client.IgnoreNotFound(err)
		}
		patch := client.MergeFrom(conv.DeepCopy())
		found := false
		for i := range conv.Status.Runs {
			run := &conv.Status.Runs[i]
			if run.RunID != runID {
				continue
			}
			found = true
			if run.DeliveredTo(channel) {
				return nil
			}
			run.Delivered = append(run.Delivered, channel)
		}
		if !found {
			// The run aged out of the bounded list. Nothing is owed — a run that
			// is no longer recorded cannot be re-derived either.
			return nil
		}
		err := q.Client.Status().Patch(ctx, &conv, patch)
		if err == nil {
			return nil
		}
		if !apierrors.IsConflict(err) {
			return err
		}
	}
	return fmt.Errorf("conflict marking run %s delivered on %s", runID, channel)
}

func (q *OpQueue) finishEnsureTopic(ctx context.Context, op *Op, res OpResult) error {
	var conv agentopsv1alpha1.Conversation
	if err := q.Client.Get(ctx, types.NamespacedName{Namespace: q.Namespace, Name: op.Conversation}, &conv); err != nil {
		return client.IgnoreNotFound(err)
	}
	patch := client.MergeFrom(conv.DeepCopy())
	cond := metav1.Condition{Type: ConditionTopicReady, Status: metav1.ConditionTrue, Reason: "TopicCreated",
		Message: "channel " + op.Channel}
	if res.Error != "" {
		cond.Status = metav1.ConditionFalse
		cond.Reason = "AdapterError"
		cond.Message = "channel " + op.Channel + ": " + res.Error
	} else if res.ThreadID == "" {
		cond.Status = metav1.ConditionFalse
		cond.Reason = "AdapterError"
		cond.Message = "channel " + op.Channel + ": adapter completed ensure-topic without a thread id"
	} else if existing := conv.ThreadFor(op.Channel); existing == nil {
		conv.Status.Threads = append(conv.Status.Threads, agentopsv1alpha1.ThreadBinding{
			Channel: op.Channel, ThreadID: res.ThreadID,
		})
	} else {
		// A REOPEN re-establishing an archived thread. Whatever came back is
		// the thread now: an adapter that honoured the hint returns the same id
		// and the conversation continues where it left off, one that could not
		// returns a fresh one. Both are recorded the same way, because both are
		// the truth about that transport.
		for i := range conv.Status.Threads {
			if conv.Status.Threads[i].Channel == op.Channel {
				conv.Status.Threads[i].ThreadID = res.ThreadID
			}
		}
	}
	if res.Error == "" && res.ThreadID != "" {
		// No longer archived: there is a live thread here again.
		kept := conv.Status.ThreadsArchived[:0]
		for _, c := range conv.Status.ThreadsArchived {
			if c != op.Channel {
				kept = append(kept, c)
			}
		}
		conv.Status.ThreadsArchived = kept
	}
	apimeta.SetStatusCondition(&conv.Status.Conditions, cond)
	if err := q.Client.Status().Patch(ctx, &conv, patch); err != nil {
		return err
	}
	if cond.Status == metav1.ConditionFalse {
		return fmt.Errorf("ensure-topic for %s: %s", op.Conversation, cond.Message)
	}
	return nil
}

// Pending reports whether an op is queued or claimed (used by tests).
func (q *OpQueue) Pending(id string) bool {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.init()
	return q.ops[id] != nil
}

// opOriginNode names where an op came from. A conversation-bound op flows from
// its conversation; a bare notice (an unwired-source warning on a general
// surface) flows from the manager.
func opOriginNode(op *Op) *activity.NodeRef {
	if op.Conversation != "" {
		return activity.Node(activity.NodeConversation, op.Conversation)
	}
	return activity.Node(activity.NodeManager, activity.NodeManager)
}

// QueueStat is one adapter's outstanding-op picture: how deep, how old, and
// WHICH op is the oldest of each kind. The identities live here rather than in
// a metric label, because a conversation or op id as a label grows series
// without bound — metrics answer "how deep, how old", this answers "which one".
type QueueStat struct {
	Adapter string `json:"adapter"`
	// Queued ops wait for an adapter to claim them: deep-and-old means nothing
	// is polling.
	Queued int `json:"queued"`
	// Claimed ops were taken and never completed: deep-and-old means an adapter
	// is wedged mid-delivery. The two failure modes look identical from outside,
	// which is exactly why they are counted apart.
	Claimed             int     `json:"claimed"`
	OldestQueuedOpID    string  `json:"oldestQueuedOpId,omitempty"`
	OldestQueuedAgeSecs float64 `json:"oldestQueuedAgeSeconds,omitempty"`
	OldestQueuedConv    string  `json:"oldestQueuedConversation,omitempty"`

	OldestClaimedOpID    string  `json:"oldestClaimedOpId,omitempty"`
	OldestClaimedAgeSecs float64 `json:"oldestClaimedAgeSeconds,omitempty"`
	OldestClaimedConv    string  `json:"oldestClaimedConversation,omitempty"`
}

// Stats snapshots the queue per adapter. The OpQueue is in-memory by design, so
// this is the ONLY place these facts exist — no Kubernetes object carries them.
func (q *OpQueue) Stats() []QueueStat {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.init()
	byAdapter := map[string]*QueueStat{}
	oldestQueued := map[string]time.Time{}
	oldestClaimed := map[string]time.Time{}
	for _, op := range q.ops {
		st := byAdapter[op.channelType]
		if st == nil {
			st = &QueueStat{Adapter: op.channelType}
			byAdapter[op.channelType] = st
		}
		if op.claimedAt.IsZero() {
			st.Queued++
			if t, ok := oldestQueued[op.channelType]; !ok || op.enqueuedAt.Before(t) {
				oldestQueued[op.channelType] = op.enqueuedAt
				st.OldestQueuedOpID, st.OldestQueuedConv = op.ID, op.Conversation
				st.OldestQueuedAgeSecs = time.Since(op.enqueuedAt).Seconds()
			}
			continue
		}
		st.Claimed++
		if t, ok := oldestClaimed[op.channelType]; !ok || op.claimedAt.Before(t) {
			oldestClaimed[op.channelType] = op.claimedAt
			st.OldestClaimedOpID, st.OldestClaimedConv = op.ID, op.Conversation
			st.OldestClaimedAgeSecs = time.Since(op.claimedAt).Seconds()
		}
	}
	out := make([]QueueStat, 0, len(byAdapter))
	for _, st := range byAdapter {
		out = append(out, *st)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Adapter < out[j].Adapter })
	return out
}
